services:
  nginx:
    ports:
      - '${APP_PORT:-8089}:80'

  db:
    platform: linux/amd64
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'

  vite:
    build:
      context: .
      dockerfile: DockerfileVite
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    ports:
      - "5173:5173"
